export class Solicitudes {

    constructor(
        public idServicio: number,
        public idTipoRegistro: number,
        public calle: string,
        public numero: string,
        public entre_calle_1: string,
        public entre_calle_2: string,
        public comentarios: string,
        public nombre: string,
        public apellido_paterno: string,
        public apellido_materno: string,
        public email: string,
        public telefono: string,
        public Idcolonia: number,
        public iddirectivo: number,
        public idusuario: number,
        public idciudadano?: number,
        public idsolicitud?: number,
        public fecha?: string,
        public folio?: string,
        public estatus?: string,
        public foto?: any,
        public ruta?: any,
        public ciudadano?: any,
        public nombre_estatus?: string,
        public ciudadano_calle?: string,
        public ciudadano_numero?: string,
        public ciudadano_idcolonia?: number,
        public latitud?: any,
        public longitud?: any,
        public idsexo?: number,
        public imagen?: File,
        public documento?: File,
        public rutaDoc?: any,

    ) { }
}
